### ISSUE TITLE
unbrick libreSDR using jtag/openocd

### ISSUE THREAD

**Issue by gl40** [lucasmellon-ops/LibreSDR#4]
Hi,

Few month ago, trying to flash a firmware, I lost contact with my LibreSDR
USB port came silent (dmesg on computer) - DFU button does nothing.

a little life on the debug port :

$ lsusb -v
[...]
Bus 003 Device 012: ID 0403:6011 Future Technology Devices International, Ltd FT4232H Quad HS USB-UART/FI
FO IC
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0403 Future Technology Devices International, Ltd
  idProduct          0x6011 FT4232H Quad HS USB-UART/FIFO IC
  bcdDevice            8.00
  iManufacturer           1 Xilinx
  iProduct                2 Xilinx Debugger
  iSerial                 3 DebugChannel
[...]

=> There is a Xilinx debugger on ftdi FT4232 usb chipset.

I got a connection using openocd with that config file :

```
Configuration  FT4232H
adapter driver ftdi
ftdi device_desc "Xilinx Debugger"
ftdi vid_pid 0x0403 0x6011
ftdi channel 0
ftdi layout_init 0x0008 0x000b

# JTAG Configuration 
transport select jtag
adapter speed 100

###  TAPs configuration 
jtag newtap auto0 tap -irlen 6 -expected-id 0x23727093
jtag newtap auto1 tap -irlen 4 -expected-id 0x4ba00477

dap create dap0 -chain-position auto1.tap
target create my_target cortex_a -dap dap0

### reset option configuration

# reset_config trst_and_srst separate

reset_config trst_only

init
jtag init
```

and then 
```
openocd -f ocd.conf
Open On-Chip Debugger 0.12.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : clock speed 100 kHz
^[[3~Info : JTAG tap: auto0.tap tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: auto1.tap tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : my_target: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for my_target on 3333
Info : Listening on port 3333 for gdb connections
Info : JTAG tap: auto0.tap tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: auto1.tap tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
```

But I can't get the cpu to halt :
```
telnet -4 localhost 4444
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> halt
timeout waiting for DSCR bit change
Error waiting for halt
```
Also testing with gdb :
```
(gdb) monitor  halt
timeout waiting for DSCR bit change
Error waiting for halt
Protocol error with Rcmd
```

Tried playing with trst srst, no success.

Any help/advice is very welcome !!

**Comment by lucasmellon-ops** [comment]
maybe a start but 
1 ssh in
2 type "reboot"
3 interrupt the countdown
4 type "run dfu_sf"

**Comment by Floppathebig** [comment]
i bricked this thing too 
unbricking 
1.load adi image on sd card (i used rufus) https://drive.google.com/file/d/19ONRCqh4yiggQ2eTuL4DVvQgLLAYbPtA/view?usp=sharing
2.load original fw to boot partition (if you cant open boot partition in windows you need set partition letter in disk manager)
3.connect sdr to otg port and flash frm files

**Comment by gl40** [comment]
> i bricked this thing too unbricking 

1.load adi image on sd card (i used rufus) https://drive.google.com/file/d/19ONRCqh4yiggQ2eTuL4DVvQgLLAYbPtA/view?usp=sharing 

>> done : got a sdcard with three partitions

2.load original fw to boot partition (if you cant open boot partition in windows you need set partition letter in disk manager) 

>> how do I do that ? 
installed diligent agent, I see two serial ports (debug port connected to PC), but unable to connect to it with putty 

3.connect sdr to otg port and flash frm files

**Comment by gl40** [comment]
At step 1 : how to ssh in ? I tried on the serial port but I have nothing on the putty terminal. Looks like it did not boot ?

**Comment by gl40** [comment]
> i bricked this thing too unbricking 1.load adi image on sd card (i used rufus) https://drive.google.com/file/d/19ONRCqh4yiggQ2eTuL4DVvQgLLAYbPtA/view?usp=sharing 2.load original fw to boot partition (if you cant open boot partition in windows you need set partition letter in disk manager) 3.connect sdr to otg port and flash frm files

Finaly working ! On sdcard for the moment but working :-)
Thanks a lot

**Comment by gl40** [comment]
solved following Floppathebig method 
greatings !

**Comment by gl40** [comment]
solved following Floppathebig method
greatings !
